# -*- coding: utf-8 -*-

ORGANIZATION_ID_MAX_LENGTH = 32

ORGANIZATION_JOIN_CODE_MAX_LENGTH = 32

ORGANIZATION_LOGO_URL_MAX_LENGTH = 256

ORGANIZATION_NAME_MAX_LENGTH = 256

ORGANIZATION_DESC_MAX_LENGTH = 3000