# -*- coding: utf-8 -*-

USER_EMAIL_MAX_LENGTH = 200

USER_REAL_NAME_MAX_LENGTH = 200

USER_USERNAME_MAX_LENGTH = 24

USER_DESC_MAX_LENGTH = 3000

USER_PASSWORD_MIN_LENGTH = 6

USER_PASSWORD_MAX_LENGTH = 256

# One megabyte image max
USER_IMAGE_MAX_LENGTH = 1048576

USER_SALT_LENGTH = 16 # Any more isn't worth the trouble